[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"
watchPaths = ["apps/web/**"]

[deploy]
# Temporarily disable healthcheck to verify the app is working
# healthcheckPath = "/"
# healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

